add_executable(MemorySystemBenchmarks benchmark_main.cpp)
target_link_libraries(MemorySystemBenchmarks PRIVATE engine::MemorySystem MemorySystemOptions benchmark::benchmark)
if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    if(MSVC)
        target_compile_options(MemorySystemBenchmarks PRIVATE /O2 /Ob2)
    else()
        target_compile_options(MemorySystemBenchmarks PRIVATE -O3)
    endif()
endif()
