add_executable(WindowSystemBenchmarks benchmark_main.cpp)
target_link_libraries(WindowSystemBenchmarks PRIVATE engine::WindowSystem WindowSystemOptions benchmark::benchmark)
if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    if(MSVC)
        target_compile_options(WindowSystemBenchmarks PRIVATE /O2 /Ob2)
    else()
        target_compile_options(WindowSystemBenchmarks PRIVATE -O3)
    endif()
endif()
