add_executable(JobSystemBenchmarks benchmark_main.cpp)
target_link_libraries(JobSystemBenchmarks PRIVATE engine::JobSystem JobSystemOptions benchmark::benchmark)
if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    if(MSVC)
        target_compile_options(JobSystemBenchmarks PRIVATE /O2 /Ob2)
    else()
        target_compile_options(JobSystemBenchmarks PRIVATE -O3)
    endif()
endif()
