add_executable(NetSystemBenchmarks benchmark_main.cpp)
target_link_libraries(NetSystemBenchmarks PRIVATE engine::NetSystem NetSystemOptions benchmark::benchmark)
if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    if(MSVC)
        target_compile_options(NetSystemBenchmarks PRIVATE /O2 /Ob2)
    else()
        target_compile_options(NetSystemBenchmarks PRIVATE -O3)
    endif()
endif()
