add_executable(RuntimeSystemBenchmarks benchmark_main.cpp)
target_link_libraries(RuntimeSystemBenchmarks PRIVATE engine::RuntimeSystem RuntimeSystemOptions benchmark::benchmark)
if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    if(MSVC)
        target_compile_options(RuntimeSystemBenchmarks PRIVATE /O2 /Ob2)
    else()
        target_compile_options(RuntimeSystemBenchmarks PRIVATE -O3)
    endif()
endif()
